name: project
description: Projeto de design de telas para um pokedex.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  simple_animations: ^1.3.6
  dio: ^3.0.9
  flutter_mobx: ^1.1.0
  mobx: ^1.1.1
  path_provider:
  flutter_modular: ^1.1.2
  flutter_staggered_animations: "^0.1.2"
  cached_network_image: ^2.1.0+1
  md2_tab_indicator: ^1.0.2
  sliding_sheet:
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.0.3
  build_runner: ^1.8.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/pokeball_dark.png
    - assets/images/pokeball.png
    - assets/json/poke_json.txt

  fonts:
    - family: Google
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Bold.ttf.
          weight: 700

scripts:
  init: flutter pub run build_runner watch --delete-conflicting-outputs
  clear: flutter pub run build_runner clean
